### PR TITLE
basic updates 2023

### PR DESCRIPTION
**Pull request by karenword**
includes active status and Challenger -> Questioner

### CODE REVIEW

**Comment by zkamvar** [comment]
No, you do not need to worry about this failed check because what you are adding is pretty vanilla stuff, but this indicates that this repository needs to have styles updated, which I will do (see https://github.com/carpentries/styles/issues/641).

I missed this one previously because it's not listed as an official lesson.

**Comment by karenword** [comment]
Interesting. Is there a process for listing it as an official lesson, or should we create one with Trainers Leadership?

**Comment by zkamvar** [comment]
> Interesting. Is there a process for listing it as an official lesson, or should we create one with Trainers Leadership?

I think literally the way to list this as an official lesson is to add the label of `lesson` to the GitHub topics in the About box (top right of the main github page). 

That being said: because this was not on my radar, I did not include it in the list of lessons to transition to The Workbench. If we do decide to transition this particular lesson, we will need to also migrate the syllabus to index.md

**Comment by karenword** [comment]
Thanks @zkamvar . I would like to transition this lesson, but I'm not sure if that's a good idea during Trainer Training or not (runs through June). I'll create a task to follow up on this with you!

**Pull request merged**
